/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uca.unidad.uno.kdd.dialog;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import uca.unidad.uno.kdd.bean.ChequeBean;
import uca.unidad.uno.kdd.renders.ImageRender;

/**
 *
 * @author OR501695
 */
public class ChequesDlg extends javax.swing.JDialog {

    /**
     * Creates new form ChequesDlg
     * @param parent
     * @param modal
     * @param list
     */
    public ChequesDlg(java.awt.Frame parent, boolean modal, List<ChequeBean> list) {
        super(parent, modal);
        initComponents();
        setList(list);
    }
    
    public final void setList(List<ChequeBean> list){
        
        ImageRender render = new ImageRender();
        this.jTable1.setDefaultRenderer(Object.class, render);
        String titles[] = {"ID", "Nombre de archivo", "Imagen"};
        DefaultTableModel model = new DefaultTableModel(null, titles);
        
        
        String[] names = new String[list.size()];
        int x = 0;

        list.forEach((b) -> {
            JLabel lbl = new JLabel();
            
            BufferedImage image = null;
            //System.out.print(">" + b.getId());
            InputStream in = new ByteArrayInputStream(b.getCheque());
            try{
                image = ImageIO.read(in);
            }catch(IOException err){
                err.printStackTrace();
            }
            lbl.setIcon(new ImageIcon(image.getScaledInstance(300, 130, Image.SCALE_SMOOTH)));
            model.addRow(new Object[]{b.getId()+"",b.getFilename(), lbl});
        });
        this.jTable1.setModel(model);
        jTable1.setRowHeight(160);
        //jTable1.setAutoResizeMode(1);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(60);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(120);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
